name: build

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    services:
      pebble:
        image: letsencrypt:pebble
        ports:
          - 14000:14000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
          check-latest: true
      - name: Set up Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set up CI
        run: |
          go install github.com/jsha/minica@v1.0.2
          $(go env GOPATH)/bin/minica -ca-cert pebble.minica.pem -ca-key pebble.minica.key.pem -domains localhost,pebble -ip-addresses 127.0.0.1
          go install github.com/letsencrypt/pebble/v2/...@v2.4.0
          $(go env GOPATH)/bin/pebble -config ./pebble-config.json > /dev/null 2>&1 &
      - name: Run Build
        run: make check
      - name: Run SonarQube
        uses: sonarsource/sonarcloud-github-action@master